### PR TITLE
Add web context.

### PR DESCRIPTION
**Pull request by ghost**
It can be helpful to have the setup of the web context parameter. Especially behind a proxy.

### CODE REVIEW

**Comment by ghost** [comment]
Could you please consider this enhancement with a fresh eye? The travis crash is due to the requirements part, especially the openjdk-8-jdk installation.

```
TASK [geerlingguy.java : Ensure Java is installed.] ****************************
failed: [localhost] (item=[u'openjdk-8-jdk']) => {"failed": true, "item": ["openjdk-8-jdk"], "msg": "No package matching 'openjdk-8-jdk' is available"}
```

**Comment by geerlingguy** [comment]
Can you please rebase since a lot has changed to get tests passing again?

**Comment by ghost** [comment]
This improvement is cursed!
```
Requirements file detected; installing dependencies.
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.7.2.tar.gz
 [ERROR]: failed to download the file: ('The read operation timed out',)
 [WARNING]: - geerlingguy.mysql was NOT installed successfully.
```
How can I relaunch the travis tests?
I try to turn the travis in green with this wizardry:
```
git commit --amend
git push origin web.context --force
```

**Comment by geerlingguy** [comment]
You can ping me and I'll relaunch the tests too—though amending a commit will be more immediate, since I only get to mentions once or twice a day :)

**Comment by ghost** [comment]
It's quite frustrating to trigger a red light for this kind of _non-issue_.
Anyway, this is validated.

Rebased.

**Pull request merged**
