### PR TITLE
Fixes #10 : Add validate_certs: no to avoid the fail of Download task.

### LINKED ISSUE #10: Download Certificate_Verify_Failed
On my sandbox Debian GNU/Linux 8.4 (jessie), I am stuck with this error message:

```
TASK [geerlingguy.sonar : Download Sonar.] *************************************
fatal: [sandbox-sonar]: FAILED! => {"changed": false, "dest": "/root/sonarqube-4.5.6.zip", "failed": true, "msg": "Request failed", "response": "Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>", "state": "absent", "status_code": -1, "url": "https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip"}
```

I tried and succeed with wget https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-4.5.6.zip
I am a bit confused with this, I beg your pardon I cannot help on this.

### PR DESCRIPTION
**Pull request by ghost**
I prefer to set the default value of sonar_validate_certs to 'no', because 'yes' is the default value of the get_url module, and that is a non-sense to override with the exact same value to me.

Source: https://docs.ansible.com/ansible/get_url_module.html

### CODE REVIEW

**Comment by geerlingguy** [comment]
@olo-dw - I'd rather default it to `yes`, as it's always better to leave things like that enabled, and only disable if you know what you're doing...

**Comment by ghost** [comment]
I changed the default value to yes.

**Comment by ghost** [comment]
Is that correct for you? Or should I modify something else?

**Comment by ghost** [comment]
The failing check does not seem to be related to the PR...
I have to find out why the "LTS test" reclaims a start, and breaks the idempotence. 

```
TASK [ansible-role-sonar : Ensure Sonar is running and set to start on boot.] **
changed: [localhost]
```

**Comment by ghost** [comment]
Rebased.

**Pull request merged**
